---
kind: Service
apiVersion: v1
metadata:
  name: exampleservice
spec:
  selector:
    app: exampleapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8082
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampledeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      containers:
        - name: exampleapp
          image: carloscharnhorst2/exampleapp 
          ports:
            - containerPort: 8080
